# docker-compose.dev.yml
# Service Geliştirme ortamı

networks:
  sentiric-net:
    name: "${NETWORK_NAME:-sentiric-net}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
  
# volumes:
  # [infra]: Temel Altyapı (Infrastructure Layer)
  # --------------------------------------------------

services:
  # [capability-tts]: Konuşma Sentezleme Yetenekleri (TTS Capabilities)
  # --------------------------------------------------  
  tts-styletts2-service:
    image: ghcr.io/sentiric/sentiric-tts-styletts2-service:${TAG:-latest}
    env_file: ["${ENV_FILE_PATH}"]
    volumes: 
      - "${CONFIG_REPO_PATH}:/sentiric-config:ro"
      - "${CERTIFICATES_REPO_PATH}:/sentiric-certificates:ro"
      - "${ASSETS_REPO_PATH}:/sentiric-assets:ro"
    ports: 
      - "14040:${TTS_STYLETTTS2_SERVICE_HTTP_PORT:-14040}"
      - "14041:${TTS_STYLETTTS2_SERVICE_GRPC_PORT:-14041}"
      - "14042:${TTS_STYLETTTS2_SERVICE_METRICS_PORT:-14042}"          
    networks:
      sentiric-net:
        ipv4_address: ${TTS_STYLETTTS2_SERVICE_IPV4_ADDRESS}
    dns:
      - ${PRIMARY_DNS:-8.8.8.8}
      - ${SECONDARY_DNS:-1.1.1.1}        
    restart: always  